### PR TITLE
Use array for mapping day 2

### PR DESCRIPTION
**Pull request by joep-nl**
Reduced day2 to 103b

### CODE REVIEW

**Comment by xem** [comment]
Wow nice! I think you can save 4 extra chars by removing parenthesis around string params:

split\`
\`

join\`+\`

can you please do it and include your score in bytes in your commit message?
thanks!

**Comment by joep-nl** [comment]
> can you please do it and include your score in bytes in your commit message?
> thanks!

Done. Was able to remove more bytes using charcodes. The solutions for a and b are the same up to an array.

**Comment by xem** [comment]
Ooh very smart!
I'm gonna publish these scores on Twitter.
What's your twitter name?

**Comment by joep-nl** [comment]
> Ooh very smart! I'm gonna publish these scores on Twitter. What's your twitter name?

@jongdejoep

**Comment by joep-nl** [comment]
> Ooh very smart! I'm gonna publish these scores on Twitter. What's your twitter name?

Do you want comments describing what the code does?

**Comment by xem** [comment]
You can add comments in the file yes, if you don't mind :)

**Pull request merged**
