### PR TITLE
Day3 106

### PR DESCRIPTION
**Pull request by joep-nl**

### CODE REVIEW

**Comment by xem** [comment]
ahah you're too fast, I haven't read the day 3 yet. I let you do your commits and I will merge tomorrow :) thanks

**Comment by joep-nl** [comment]
> ahah you're too fast, I haven't read the day 3 yet. I let you do your commits and I will merge tomorrow :) thanks

hahah i think i'm done for today. need to do some other work too. i think day3 can be optimized by using `b.reverse()`, but that reverses in place..

**Comment by xem** [comment]
quick ideas:

1) "...".charCodeAt(0) => "...".charCodeAt() 

2) find intersection between 2 arrays: a1.filter(v=>a2.includes(v))

3) maybe something with a regexp? s1.find(new Regex`[${s2}]`)

**Comment by xem** [comment]
4) "abc"split`` => [..."abc"]

**Comment by xem** [comment]
Hi, I have two pretty similar 99b solutions:

clean:
```
a=i=>i.split`
`.reduce((a,b)=>a+([...b].findLast(x=>b.indexOf(x)<b.length/2).charCodeAt()-38)%58,0)
```

dirty:

```
t=0,a=i=>(i.split`
`.map(b=>t+=([...b].findLast(x=>b.indexOf(x)<b.length/2).charCodeAt()-38)%58),t)
```

any idea how to improve one of them?

**Pull request merged**
