### PR TITLE
54

### PR DESCRIPTION
**Pull request by subzey**
Sorry for the final newline, I'm using the GH web editor and it seems to add the final newline by itself

### CODE REVIEW

**Comment by xem** [comment]
Congrats - sorry, I pushed an update with the part 2 of the challenge in the meantime, so there's a conflict

**Comment by subzey** [comment]
Yup, rebased my changes onto yours. Got rid of that final newline also

**Comment by xem** [comment]
Thanks! I thought you would golf part 2 too but I can do it myself :)
... unless you have an idea to shorten my code that sums tha 3 biggest lists?

eval([...].sort((a,b)=>b-a).slice(0,3).join\`+\`)

maybe something like

(i=[...])[0]+i[1]+i[2]

**Comment by subzey** [comment]
At the first glance I cannot see how it could be golfed even more. So I'll just keep it as is. For now :grinning:

**Comment by xem** [comment]
I'm trying the (i=[...].sort(...))[0]+i[1]+i[2] approach, we'll see :)

**Comment by subzey** [comment]
`[a,b,c]=[...].sort(...),a+b+c` might be sliiightly shorter

**Comment by xem** [comment]
hmmm it tells me a, b, c are undefined
update: it works with parenthesis

**Pull request merged**
