### PR TITLE
Day2 81b. (use direct formula)

### PR DESCRIPTION
**Pull request by joep-nl**
I found a direct formula for the score. It reduced the length from 82b to 81b. However, the code is difficult to explain now..

### CODE REVIEW

**Comment by xem** [comment]
amazing! is something similar doable for part 2?

**Comment by joep-nl** [comment]
> amazing! is something similar doable for part 2?

Definitely, will do that later today. I've also added some comments.

**Comment by joep-nl** [comment]
btw, it is almost a shame that all the previous solutions, which could be totally different, are no longer easy to find. any ideas on how to keep track of these? maybe using separate files for every solution?

**Comment by xem** [comment]
We could copy them in the readme comment at the beginning of the file

// Previous solutions:
// 88b:...
// 84b:...

 ?

**Comment by joep-nl** [comment]
> We could copy them in the readme comment at the beginning of the file
> 
> // Previous solutions: // 88b:... // 84b:...
> 
> ?

If we add comments to every solution, then the files can get quite large. 

Maybe place every day in a folder and name files after the number of characters. Only make new files if the solutions differ enough?

**Comment by xem** [comment]
Fine for me! 
Btw, have you seen my comment about day 3 part 1?
Also, day 3 part 2 sounds a bit annoying, we have to find the common char between each group of 3 strings... Not sure how to solve this smartly yet

**Comment by joep-nl** [comment]
> Btw, have you seen my comment about day 3 part 1?

I saw. I am not that experienced with regex. I also didn't know about `findLast`, nice! 

> Also, day 3 part 2 sounds a bit annoying, we have to find the common char between each group of 3 strings... Not sure how to solve this smartly yet

The first approach I think of is finding all the intersections with `filter` and intersecting them again with `find`.

**Pull request merged**
